Build a Reusable Styled Button Component
jessieyu1/weather-app pull request #17
Opened 2021-11-01 10:28 UTC by jessieyu1

changes:
 Build the directory
 Use the template to get started
 Build the component

close #11

2021-11-01 10:28 UTC, jessieyu1 commented
![Nov-01-2021 18-28-38](https://user-images.githubusercontent.com/61171021/139658072-0f16e89c-edbb-4d27-88d4-4bbe17056a47.gif)

2021-11-01 11:00 UTC, aubreynicoll requested changes
Plenty of stuff to be done here. One of them is a rather large and important design decision: Whether this should be reduced to a simple styled component, or kept as a "normal" React component that receives props.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +  // eslint-disable-next-line no-console
Definitely remove this. Always a good idea to listen to what ESLint has to say (although there isn't even a console.log statement on the following line)

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/index.stories.jsx
> +    // eslint-disable-next-line no-console
This is a good example of ignoring ESLint. Definitely need to have logging in Storybook. Good job!

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +const Button = ({ text }) => (
Since this button component is all style (there's no internal logic), you might think about just exporting ButtonStyle as the default. Then you could get rid of props completely, and just wrap text with the component as though it were a normal button.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +const Button = ({ text }) => (
It is my preference to use the props (but that's just my choice and you don't have to).

In the case of using props, I'd also look at requiring an onClick function.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +  <ButtonStyle>{text}</ButtonStyle>
In React, we often want to explicitly set the button attribute type to "button", like so:

`<button type="button" />`

This will prevent it from ever accidentally submitting a form or something like that.

HOWEVER! If you want to turn this into only a styled component, then you don't need to do it here. Instead, you need to remember to do it when you USE the component. If you want this to be a more "normal" component that uses props, then you better set it here.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +  cursor: 'pointer',
Please check that the cursor doesn't do this anyway. Pretty sure all buttons do this by default.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +  '&:hover': {
Hover is a great pseudoclass to use here. For buttons, :active is also really good to use. Why don't you try setting an active style and see what it does.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +
We shouldn't leave empty lines of code like this.

Generally speaking, empty lines are great if the code has different purpose (as when we have several function definitions next to each other), but for CSS it's fine to just lump it all together.

2021-11-01 11:00 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +  tabSize: '2',
Why is this here?

2021-11-02 04:45 UTC, aubreynicoll requested changes
Still have a ways to go. Reusability has taken a big hit in these recent changes. Remember, we want a  styled button that can be used anywhere and for any purpose.

2021-11-02 04:45 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +    <span> Search Weather</span>
Remember that our goal is to make a reusable button component. By hard-coding the words "Search Weather" here, how could we ever use it for anything else?

2021-11-02 04:45 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +    <span role="img" aria-label="Search">   🔍</span>
Hard-coding text and icons here is very bad for reusability. If this is a button, then can't we just pass these in when we implement the button in our landing page?

Also, this is not a good way to do icons. I recommend using SVGs, which can be turned into React components. I can show you how later.

2021-11-02 04:45 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +  ':active': {
It is good that you've added an active style, however, you should make it different than the hover style. The active style appears *while* the user is clicking the button, so it's a very brief effect, but it does show the user that their click has registered. Buttons look really weird without this.

2021-11-02 05:01 UTC, jessieyu1 commented
![Nov-02-2021 13-00-29](https://user-images.githubusercontent.com/61171021/139789271-0c01187c-174b-45a7-8985-c0dcd958eaf8.gif)

2021-11-02 06:33 UTC, aubreynicoll requested changes

2021-11-02 06:33 UTC, aubreynicoll commented on src/Components/Button/index.jsx
> +export default ButtonStyle;
Remember, the default export should have the same name as the folder, in this case Button.

2021-11-02 06:33 UTC, aubreynicoll commented on src/Components/Button/styles.js
> +    backgroundColor: '#red',
This code won't work, please remove the hashtag. Also, are you sure you want to use pure red for this?

2021-11-02 10:41 UTC, aubreynicoll approved these changes

2021-11-02 10:41 UTC, merged